name: flutter_app
description: 'Kumpara Mobil Uygulaması'
publish_to: 'none'

version: 1.0.11+16

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # Dil ve Yerelleştirme desteği
  flutter_localizations:
    sdk: flutter
    
  # WebView ve Web Motorları
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.0.0
  webview_flutter_wkwebview: ^3.14.0
  app_settings: ^5.1.1
  # Dosya Seçme (Android için eklediğimiz)
  file_picker: ^8.0.0

  # Link ve URL Yönetimi 
  url_launcher: ^6.2.5
  app_links: ^6.3.2
  
  # Reklam ve Analiz 
  google_mobile_ads: ^5.0.0
  
  # Uygulama ve Cihaz Bilgisi
  package_info_plus: ^8.0.0
  upgrader: ^10.3.0
  
  # Bildirim ve Depolama
  onesignal_flutter: 5.4.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # İkon dosyan assets içinde olduğu için burayı eklemelisin
  assets:
    - assets/icon.png

# Uygulama ikonu ayarları
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"